name: Generate Metrics

on:
  schedule: [{cron: "0 * * * *"}] # every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_colors: solid # solid blocks
          plugin_isocalendar_legend: no
          plugin_isocalendar_shape: 3d # this makes it 3D blocks

