name: Metrics

on:
  # Schedule updates (every hour)
  schedule: [{cron: "0 * * * *"}]
  # Allow manual and push triggers
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub Token
          token: ${{ secrets.METRICS_TOKEN }}

          # Output file name
          filename: metrics.svg

          # User setup
          user: foevertigo
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta

          # Calendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Languages plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # LeetCode plugin
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: foevertigo

          # Music plugin
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_token: ${{ secrets.MUSIC_TOKEN }}

          # Stargazers plugin
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 14
